#! /bin/bash
if [ -f /opt/datadog-agent/agent/datadog-cert.pem ]; then
  wget https://raw.githubusercontent.com/DataDog/dd-agent/master/datadog-cert.pem
  cp datadog-cert.pem > /opt/datadog-agent/agent/datadog-cert.pem
  rm datadog-cert.pem
  exit
fi
